platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'



target 'KinoApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )



  target 'KinoAppTests' do
    inherit! :complete
    # Pods for testing
  end

  use_flipper!()
  post_install do |installer|
    react_native_post_install(installer)
  end

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
end

# target 'KinoApp-tvOS' do
#   # Pods for KinoApp-tvOS

#   target 'KinoApp-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end
